
import os.path
import platform

Import( 'env' )
env = env.Copy( )

generated = os.path.join( env[ 'VISE_BIN_DIR' ], 'run_example' )

dlLibs = [ ]
if platform.system( ) == 'Linux' :
    dlLibs = [ 'dl' ]

env.Program( generated,
             'ViseExampleTest.cpp',
             LIBS = [ 'vise',
                      'cppunit' ] + dlLibs + \
             env[ 'BOOST_LIBS' ] )
